server:
  port: 7001
eureka:
  instance:
    hostname: eureka1
  #    hostname: localhost  # 定义 Eureka 实例所在的主机名称
  client:
    fetch-registry: false  #是否从eureka中获取注册信息,本身就是eureka,不需要,设置为false
    register-with-eureka: false  #是否要注册到eureka上,本身就是eureka,不需要,设置为false
    service-url:
      defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false       #设置为false表示关闭保护模式
spring:
  security:
    user:
      name: admin
      password: enjoy