server:
  port: 8080
spring:
  application:
    name: microcloud-provider-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/distributed?serverTimezone=GMT%2B8
    username: root
    password: 123456
#  security:
#    user:
#      name: admin
#      password: enjoy
#      roles: USER
mybatis:
  mapper-locations: classpath:mapping/*.xml
logging:
  level:
    cn.enjoy.mapper: debug

